import "reflect-metadata";
import { TypedJSON } from "typedjson";
import { Tag, TagBucket } from "@/model/Tag";

// tslint:disable-next-line: max-line-length
const tagsPojo = [
  { value: "1940S", category: "Other", count: 186 },
  { value: "1950S", category: "Other", count: 74 },
  { value: "1960S", category: "Other", count: 161 },
  { value: "1970S", category: "Other", count: 201 },
  { value: "1980S", category: "Other", count: 311 },
  { value: "1990S", category: "Other", count: 170 },
  { value: "2000S", category: "Other", count: 190 },
  { value: "2010S", category: "Other", count: 330 },
  { value: "2011", category: "Other", count: 13 },
  { value: "2013", category: "Other", count: 12 },
  { value: "2015", category: "Other", count: 89 },
  { value: "3/4", category: "Tempo", count: 2582 },
  { value: "4/4", category: "Tempo", count: 25588 },
  { value: "A Cappella", category: "Music", count: 24 },
  { value: "Acid Jazz", category: "Music", count: 142 },
  { value: "Acoustic Audio Recordings", category: "Music", count: 26 },
  { value: "Acoustic Blues", category: "Music", count: 16 },
  { value: "Acoustic Pop", category: "Music", count: 89 },
  { value: "Adult Alternative", category: "Music", count: 83 },
  { value: "Adult Contemporary", category: "Music", count: 275 },
  { value: "Adult Standards", category: "Music", count: 658 },
  { value: "African", category: "Music", count: 31 },
  { value: "Afropop", category: "Music", count: 21 },
  { value: "Alan", category: "Other", count: 42 },
  { value: "Album Oriented Rock", category: "Music", count: 26 },
  { value: "Album Rock", category: "Music", count: 202 },
  { value: "Alek", category: "Other", count: 17 },
  { value: "Alexa", category: "Other", count: 11 },
  { value: "Alexis", category: "Other", count: 11 },
  { value: "Allison", category: "Other", count: 26 },
  { value: "Ally", category: "Other", count: 13 },
  { value: "Alt Country Rock", category: "Music", count: 19 },
  { value: "Alt", category: "Other", count: 86 },
  { value: "Alternative Dance", category: "Music", count: 35 },
  { value: "Alternative Metal", category: "Music", count: 34 },
  { value: "Alternative R&B", category: "Music", count: 31 },
  { value: "Alternative Rock", category: "Music", count: 47 },
  { value: "Alternative", category: "Music", count: 1647 },
  { value: "Ambient", category: "Music", count: 112 },
  { value: "Amercian", category: "Style", count: 155 },
  { value: "American", category: "Style", count: 3811 },
  { value: "Anthem Worship", category: "Music", count: 13 },
  { value: "Argentine Rock", category: "Music", count: 19 },
  { value: "Art Pop", category: "Music", count: 37 },
  { value: "Art Rock", category: "Music", count: 75 },
  { value: "Artem", category: "Other", count: 42 },
  { value: "Asian", category: "Music", count: 23 },
  { value: "Atl Hip Hop", category: "Music", count: 46 },
  { value: "Australian Dance", category: "Music", count: 54 },
  { value: "Australian Electropop", category: "Music", count: 11 },
  { value: "Australian Indie", category: "Music", count: 21 },
  { value: "Australian Pop", category: "Music", count: 195 },
  { value: "Australian Rock", category: "Music", count: 11 },
  { value: "Australian Talent Show", category: "Music", count: 33 },
  { value: "Axe", category: "Music", count: 12 },
  { value: "Bachata", category: "Music", count: 212 },
  { value: "Baile Pop", category: "Music", count: 28 },
  { value: "Baladas Y Boleros", category: "Music", count: 78 },
  { value: "Balkan Brass", category: "Music", count: 11 },
  { value: "Ballroom", category: "Music", count: 194 },
  { value: "Baroque Pop", category: "Music", count: 139 },
  { value: "Bebop", category: "Music", count: 178 },
  { value: "Belgian Pop", category: "Music", count: 13 },
  { value: "Big Band", category: "Music", count: 874 },
  { value: "Big Room", category: "Music", count: 111 },
  { value: "Bindi", category: "Other", count: 18 },
  { value: "Bluegrass", category: "Music", count: 22 },
  { value: "Blues / Folk", category: "Music", count: 338 },
  { value: "Blues Rock", category: "Music", count: 133 },
  { value: "Blues", category: "Music", count: 1034 },
  { value: "Bolero Cubano", category: "Music", count: 14 },
  { value: "Bolero", category: "Music", count: 137 },
  { value: "Bonner", category: "Other", count: 13 },
  { value: "Boogaloo", category: "Music", count: 394 },
  { value: "Boogie Woogie", category: "Music", count: 23 },
  { value: "Bop Jazz", category: "Music", count: 31 },
  { value: "Bossa Nova", category: "Music", count: 77 },
  { value: "Bow Pop", category: "Music", count: 57 },
  { value: "Boy Band", category: "Music", count: 58 },
  { value: "Brazilian Jazz", category: "Music", count: 22 },
  { value: "Brazilian", category: "Music", count: 100 },
  { value: "Brill Building Pop", category: "Music", count: 185 },
  { value: "British Invasion", category: "Music", count: 34 },
  { value: "British Soul", category: "Music", count: 50 },
  { value: "Britpop", category: "Music", count: 11 },
  { value: "Broadway And Vocal", category: "Music", count: 97 },
  { value: "Broadway", category: "Music", count: 17 },
  { value: "Brostep", category: "Music", count: 29 },
  { value: "Bubblegum Dance", category: "Music", count: 41 },
  { value: "Bubblegum Pop", category: "Music", count: 64 },
  { value: "Canadian Contemporary R&B", category: "Music", count: 21 },
  { value: "Canadian Country", category: "Music", count: 14 },
  { value: "Canadian Electronic", category: "Music", count: 13 },
  { value: "Canadian Electropop", category: "Music", count: 13 },
  { value: "Canadian Hip Hop", category: "Music", count: 13 },
  { value: "Canadian Indie", category: "Music", count: 11 },
  { value: "Canadian Latin", category: "Music", count: 13 },
  { value: "Canadian Pop", category: "Music", count: 189 },
  { value: "Canadian Rock", category: "Music", count: 13 },
  { value: "Canadian Singer Songwriter", category: "Music", count: 13 },
  { value: "Candy Pop", category: "Music", count: 33 },
  { value: "Cantautor", category: "Music", count: 35 },
  { value: "Caribbean", category: "Music", count: 135 },
  { value: "Carlos", category: "Other", count: 17 },
  { value: "Ccm", category: "Music", count: 34 },
  { value: "Celtic Rock", category: "Music", count: 11 },
  { value: "Celtic", category: "Music", count: 48 },
  { value: "Chamber Pop", category: "Music", count: 34 },
  { value: "Champeta", category: "Music", count: 25 },
  { value: "Channel Pop", category: "Music", count: 23 },
  { value: "Chanson", category: "Music", count: 26 },
  { value: "Charanga", category: "Music", count: 22 },
  { value: "Cheryl", category: "Other", count: 31 },
  { value: "Children's Music", category: "Music", count: 82 },
  { value: "Childrens", category: "Music", count: 82 },
  { value: "Chilean Rock", category: "Music", count: 23 },
  { value: "Chris", category: "Other", count: 15 },
  { value: "Christian / Gospel", category: "Music", count: 180 },
  { value: "Christian Alternative Rock", category: "Music", count: 25 },
  { value: "Christian Music", category: "Music", count: 29 },
  { value: "Christian Pop", category: "Music", count: 14 },
  { value: "Christmas Classics", category: "Other", count: 16 },
  { value: "Christmas Hits", category: "Other", count: 32 },
  { value: "Christmas Pop", category: "Other", count: 32 },
  { value: "Christmas Time", category: "Other", count: 18 },
  { value: "Christmas", category: "Music", count: 68 },
  { value: "Classic Canadian Rock", category: "Music", count: 16 },
  { value: "Classic Colombian Pop", category: "Music", count: 25 },
  { value: "Classic Girl Group", category: "Music", count: 35 },
  { value: "Classic Italian Pop", category: "Music", count: 11 },
  { value: "Classic Rhythm And Blues", category: "Music", count: 25 },
  { value: "Classic Rock", category: "Music", count: 287 },
  { value: "Classic Schlager", category: "Music", count: 15 },
  { value: "Classic Soul", category: "Music", count: 130 },
  { value: "Classic Soundtrack", category: "Music", count: 22 },
  { value: "Classic Venezuelan Pop", category: "Music", count: 17 },
  { value: "Classical Crossover", category: "Music", count: 12 },
  { value: "Classical", category: "Music", count: 311 },
  { value: "Classify", category: "Music", count: 18 },
  { value: "Club", category: "Style", count: 381 },
  { value: "Colombian Hip Hop", category: "Music", count: 17 },
  { value: "Colombian Indie", category: "Music", count: 11 },
  { value: "Colombian Pop", category: "Music", count: 212 },
  { value: "Colombian Rock", category: "Music", count: 23 },
  { value: "Columbian", category: "Style", count: 800 },
  { value: "Comedy / Spoken Word", category: "Music", count: 59 },
  { value: "Comedy", category: "Music", count: 45 },
  { value: "Comic", category: "Music", count: 19 },
  { value: "Compilations", category: "Music", count: 54 },
  { value: "Complextro", category: "Music", count: 19 },
  { value: "Compositional Ambient", category: "Music", count: 12 },
  { value: "Conscious Hip Hop", category: "Music", count: 21 },
  { value: "Contemporary Christmas", category: "Other", count: 15 },
  { value: "Contemporary Country", category: "Music", count: 212 },
  { value: "Contemporary Folk", category: "Music", count: 45 },
  { value: "Contemporary Latin", category: "Music", count: 48 },
  { value: "Contemporary Post Bop", category: "Music", count: 28 },
  { value: "Contemporary R&B", category: "Music", count: 58 },
  { value: "Contemporary", category: "Music", count: 31 },
  { value: "Contemporary", category: "Style", count: 324 },
  { value: "Cool Jazz", category: "Music", count: 172 },
  { value: "Country Dawn", category: "Music", count: 61 },
  { value: "Country Gospel", category: "Music", count: 23 },
  { value: "Country Pop", category: "Music", count: 48 },
  { value: "Country Road", category: "Music", count: 120 },
  { value: "Country Rock", category: "Music", count: 62 },
  { value: "Country", category: "Music", count: 1138 },
  { value: "Coverchill", category: "Music", count: 19 },
  { value: "Cuban Alternative", category: "Music", count: 33 },
  { value: "Cuban Rumba", category: "Music", count: 411 },
  { value: "Cuban", category: "Music", count: 14 },
  { value: "Cuban", category: "Style", count: 134 },
  { value: "Cubaton", category: "Music", count: 209 },
  { value: "Cumbia Chilena", category: "Music", count: 52 },
  { value: "Cumbia Paraguaya", category: "Music", count: 12 },
  { value: "Cumbia Pop", category: "Music", count: 71 },
  { value: "Cumbia Ranchera", category: "Music", count: 32 },
  { value: "Cumbia Sonidera", category: "Music", count: 22 },
  { value: "Cumbia Villera", category: "Music", count: 72 },
  { value: "Cumbia", category: "Music", count: 179 },
];

describe("tags loading", () => {
  it("should load tags", () => {
    const tags = TypedJSON.parseAsArray(tagsPojo, Tag);
    expect(tags).toBeDefined();
    expect(tags[0]).toBeInstanceOf(Tag);
  });

  it("should bucketize", () => {
    const tags = TypedJSON.parseAsArray(tagsPojo, Tag);
    const bucketized = TagBucket.bucketize(tags, 10);
    expect(bucketized).toBeDefined();
    expect(bucketized[0]).toBeInstanceOf(TagBucket);
    expect(bucketized.length).toEqual(tags.length);
    expect(bucketized.reduce((max, t) => Math.max(max, t.count ?? 0), 0) === 9);
  });

  it("should negate", () => {
    const tag = new Tag({ value: "Rumba", category: "Dance" });
    expect(tag.key).toEqual("Rumba:Dance");
    const neg = tag.negated;
    expect(neg.key).toEqual("!Rumba:Dance");
    const dneg = neg.negated;
    expect(dneg.key).toEqual("Rumba:Dance");
  });
});
