compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

packageExtensions:
  deasync@*:
    dependencies:
      node-gyp: latest

yarnPath: .yarn/releases/yarn-4.1.0.cjs
