/**
 * Test fixture for admin-users page.
 * Represents a realistic but minimal AdminUsersModel payload.
 */
export const model = {
  users: [
    {
      id: "user-1",
      userName: "alice",
      email: "alice@example.com",
      emailConfirmed: true,
      isPseudo: false,
      startDate: "2022-03-15T10:00:00",
      lastActive: "2024-11-20T14:30:00",
      hitCount: 42,
      lifetimePurchased: 19.99,
      subscriptionLevel: 2,
      privacy: 255,
      canContact: 5,
      servicePreference: "S",
      failedCardAttempts: 0,
      roles: ["premium"],
      logins: ["Spotify"],
    },
    {
      id: "user-2",
      userName: "bob",
      email: "bob@example.com",
      emailConfirmed: false,
      isPseudo: false,
      startDate: "2023-07-01T08:00:00",
      lastActive: "1900-01-01T00:00:00",
      hitCount: 5,
      lifetimePurchased: 0,
      subscriptionLevel: 0,
      privacy: 255,
      canContact: 0,
      servicePreference: null,
      failedCardAttempts: 2,
      roles: [],
      logins: ["Microsoft"],
    },
    {
      id: "user-3",
      userName: "carol|P",
      email: "carol@music4dance.net",
      emailConfirmed: true,
      isPseudo: true,
      startDate: "2021-01-10T00:00:00",
      lastActive: "2024-12-01T09:15:00",
      hitCount: 150,
      lifetimePurchased: 0,
      subscriptionLevel: 0,
      privacy: 0,
      canContact: 0,
      servicePreference: "SG",
      failedCardAttempts: 0,
      roles: [],
      logins: ["Spotify", "Google"],
    },
    {
      id: "user-4",
      userName: "DEL:dave",
      email: "dave@example.com",
      emailConfirmed: true,
      isPseudo: false,
      startDate: "2020-06-01T00:00:00",
      lastActive: "2021-01-15T00:00:00",
      hitCount: 0,
      lifetimePurchased: 0,
      subscriptionLevel: 0,
      privacy: 255,
      canContact: 0,
      servicePreference: null,
      failedCardAttempts: 0,
      roles: [],
      logins: [],
    },
  ],
  allRoles: ["dbAdmin", "premium", "trial"],
  services: [
    { cid: "S", name: "Spotify" },
    { cid: "A", name: "Amazon" },
    { cid: "G", name: "Google" },
  ],
};
