// <auto-generated />
namespace SongDatabase.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddDanceRating : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddDanceRating));
        
        string IMigrationMetadata.Id
        {
            get { return "201310022012320_AddDanceRating"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
