using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace m4dModels.Tests;

[TestClass]
public class ArtistIndexFileTests
{
    private static ArtistIndex BuildSample(DateTime built) => ArtistIndex.Build(
    [
        ["The Beatles"],
        ["The Beatles", "Billy Preston"],
        ["Michael Bublé"],
        ["Michael Buble", "Meghan Trainor"],
    ], built);

    [TestMethod]
    public void SaveToJson_RoundTripsEntriesAndOrder()
    {
        var built = new DateTime(2026, 9, 16, 8, 30, 0, DateTimeKind.Utc);
        var original = BuildSample(built);
        var reloaded = ArtistIndex.LoadFromJson(original.SaveToJson());

        Assert.AreEqual(original.Count, reloaded.Count);
        CollectionAssert.AreEqual(
            original.InBucket("B").ToList(), reloaded.InBucket("B").ToList());
        CollectionAssert.AreEqual(
            original.Top(10).ToList(), reloaded.Top(10).ToList());
    }

    [TestMethod]
    public void SaveToJson_KeepsBuildTimeInUtc()
    {
        // Staleness is measured against DateTime.UtcNow, so a round trip that came back as local
        // time would shift the snapshot's age by the server's offset.
        var built = new DateTime(2026, 9, 16, 8, 30, 0, DateTimeKind.Utc);
        var reloaded = ArtistIndex.LoadFromJson(BuildSample(built).SaveToJson());

        Assert.AreEqual(built, reloaded.Built);
        Assert.AreEqual(DateTimeKind.Utc, reloaded.Built.Kind);
    }

    [TestMethod]
    public void SaveToJson_KeepsTheMergedSpellingAndCount()
    {
        var original = ArtistIndex.Build(
            [["Michael Bublé"], ["Michael Buble"], ["Michael Bublé"]], DateTime.UtcNow);
        var reloaded = ArtistIndex.LoadFromJson(original.SaveToJson());

        // Variants are merged when the snapshot is built, and the file stores that result rather
        // than the raw credits - so reloading keeps the winning spelling and the combined count
        // instead of re-deciding either.
        Assert.AreEqual(new ArtistIndexEntry("Michael Bublé", 3), reloaded.Search("buble").Single());
    }

    [TestMethod]
    public void LoadFromJson_ReturnsNullForUnusableInput()
    {
        // A snapshot is a cache; an unreadable one is worth no more than a miss.
        Assert.IsNull(ArtistIndex.LoadFromJson(null));
        Assert.IsNull(ArtistIndex.LoadFromJson(""));
        Assert.IsNull(ArtistIndex.LoadFromJson("{\"built\":\"2026-09-16T00:00:00Z\",\"artists\":{}}"));
        Assert.IsNull(ArtistIndex.LoadFromJson("not json at all"));
        Assert.IsNull(ArtistIndex.LoadFromJson("{\"built\":\"2026-09-16T00:00:00Z\",\"artists\":[1,2"));
    }

    [TestMethod]
    public async Task FileManager_PrefersTheRuntimeSnapshotOverTheFallback()
    {
        var root = TempRoot();
        try
        {
            var files = new ArtistIndexFileManager(root);
            WriteFallback(root, ArtistIndex.Build([["Fallback Artist"]]).SaveToJson());

            Assert.AreEqual("Fallback Artist", ArtistIndex.LoadFromJson(await files.Read()).Top(1).Single().Name);

            await files.Write(ArtistIndex.Build([["Runtime Artist"]]).SaveToJson());
            Assert.AreEqual("Runtime Artist", ArtistIndex.LoadFromJson(await files.Read()).Top(1).Single().Name);

            // Delete drops the runtime snapshot only - the one in source control is the floor.
            files.Delete();
            Assert.AreEqual("Fallback Artist", ArtistIndex.LoadFromJson(await files.Read()).Top(1).Single().Name);
        }
        finally
        {
            Directory.Delete(root, recursive: true);
        }
    }

    [TestMethod]
    public async Task FileManager_ReadsNullWhenThereIsNoSnapshotAtAll()
    {
        var root = TempRoot();
        try
        {
            Assert.IsNull(await new ArtistIndexFileManager(root).Read());
        }
        finally
        {
            Directory.Delete(root, recursive: true);
        }
    }

    [TestMethod]
    public async Task FileManager_LeavesNoTemporaryFilesBehind()
    {
        var root = TempRoot();
        try
        {
            var files = new ArtistIndexFileManager(root);
            await files.Write(ArtistIndex.Build([["Somebody"]]).SaveToJson());
            await files.Write(ArtistIndex.Build([["Somebody Else"]]).SaveToJson());

            CollectionAssert.AreEqual(
                new[] { "artist-index.json" },
                Directory.GetFiles(Path.Combine(root, "AppData")).Select(Path.GetFileName).Order().ToList());
        }
        finally
        {
            Directory.Delete(root, recursive: true);
        }
    }

    [TestMethod]
    public void TheShippedFallbackSnapshotIsReadable()
    {
        // It's generated by a manual harness and committed by hand, so nothing else would notice
        // a truncated or mis-serialized one until an instance came up with an empty artist index.
        var index = ArtistIndex.LoadFromJson(File.ReadAllText(ArtistIndexSnapshot.FallbackPath));

        Assert.IsNotNull(index, "The fallback snapshot in source control could not be read.");
        Assert.IsTrue(index.Count > 10000, $"Only {index.Count} artists - regenerate the snapshot.");
        Assert.AreEqual(DateTimeKind.Utc, index.Built.Kind);

        // Dated from the backup it came from, so the cache rebuilds rather than serving it for
        // six hours after a deploy.
        Assert.IsTrue(index.Built < DateTime.UtcNow, "The fallback snapshot is dated in the future.");
    }

    private static string TempRoot()
    {
        var root = Path.Combine(Path.GetTempPath(), $"m4d-artist-index-{Guid.NewGuid():N}");
        _ = Directory.CreateDirectory(root);
        return root;
    }

    private static void WriteFallback(string root, string json)
    {
        var content = Path.Combine(root, "content");
        _ = Directory.CreateDirectory(content);
        File.WriteAllText(Path.Combine(content, "artist-index-fallback.json"), json);
    }
}
