//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18046
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DanceLibrary {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DanceLibrary {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DanceLibrary() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DanceLibrary.DanceLibrary", typeof(DanceLibrary).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;Name&quot;: &quot;Swing&quot;,
        ///    &quot;Id&quot; : &quot;SWG&quot;,
        ///    &quot;MemberIds&quot; : [&quot;ECS&quot;,&quot;JIV&quot;,&quot;WCS&quot;,&quot;LHP&quot;,&quot;HST&quot;]
        ///  },
        ///  {
        ///    &quot;Name&quot;: &quot;WALTZ&quot;,
        ///    &quot;Id&quot; : &quot;WLZ&quot;,
        ///    &quot;MemberIds&quot; : [&quot;SWZ&quot;,&quot;VWZ&quot;]
        ///  },
        ///  {
        ///    &quot;Name&quot;: &quot;TANGO&quot;,
        ///    &quot;Id&quot; : &quot;TNG&quot;,
        ///    &quot;MemberIds&quot; : [&quot;TGO&quot;,&quot;ATN&quot;]
        ///  },
        ///  {
        ///    &quot;Name&quot;: &quot;Foxtrot&quot;,
        ///    &quot;Id&quot; : &quot;FXT&quot;,
        ///    &quot;MemberIds&quot; : [&quot;SFT&quot;,&quot;QST&quot;]
        ///  },
        ///].
        /// </summary>
        internal static string DanceGroups {
            get {
                return ResourceManager.GetString("DanceGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Dances&gt;
        ///  &lt;DanceType Name=&quot;Waltz&quot; Meter=&quot;3/4&quot;&gt;
        ///    &lt;DanceInstance Style=&quot;American Smooth&quot; MinTempo=&quot;28&quot; MaxTempo=&quot;30&quot;&gt;
        ///      &lt;DanceException Organization=&quot;NDCA&quot; Level=&quot;Bronze&quot; MinTempo=&quot;30&quot; MaxTempo=&quot;32&quot;/&gt;
        ///    &lt;/DanceInstance&gt;
        ///    &lt;DanceInstance Style=&quot;International Standard&quot; MinTempo=&quot;28&quot; MaxTempo=&quot;30&quot;&gt;
        ///      &lt;DanceException Organization=&quot;NDCA&quot; Competitor=&quot;Professional,Amateur&quot; Tempo=&quot;28&quot;/&gt;
        ///    &lt;/DanceInstance&gt;
        ///  &lt;/DanceType&gt;
        ///  &lt;DanceType Name=&quot;Foxtrot&quot; Me [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Dances {
            get {
                return ResourceManager.GetString("Dances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;Name&quot;: &quot;Slow Waltz&quot;,
        ///    &quot;Id&quot; : &quot;SWZ&quot;,
        ///    &quot;Meter&quot;: {
        ///      &quot;Numerator&quot;: 3,
        ///      &quot;Denominator&quot;: 4
        ///    },
        ///    &quot;Instances&quot;: [
        ///      {
        ///        &quot;Style&quot;: &quot;American Smooth&quot;,
        ///        &quot;TempoRange&quot;: {
        ///          &quot;Min&quot;: 28.0,
        ///          &quot;Max&quot;: 30.0
        ///        },
        ///        &quot;Exceptions&quot;: [
        ///          {
        ///            &quot;Organization&quot;: &quot;NDCA&quot;,
        ///            &quot;TempoRange&quot;: {
        ///              &quot;Min&quot;: 30.0,
        ///              &quot;Max&quot;: 32.0
        ///            },
        ///            &quot;Level&quot;: &quot;Bronze&quot;
        ///          }
        ///        ]
        ///      } [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JsonDances {
            get {
                return ResourceManager.GetString("JsonDances", resourceCulture);
            }
        }
    }
}
