name: CI-CLIENT

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: m4d/ClientApp/

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"

      - name: Enable Corepack
        run: corepack enable

      - name: Set Yarn global folder
        run: yarn config set globalFolder "${{ github.workspace }}/Yarn/Berry"

      - name: Install dependencies
        run: yarn install --network-timeout=300000

      - name: Run unit tests
        run: yarn run test:ci

      - name: Upload JUnit Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: junit-results
          path: "**/junit.xml"

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          junit_files: "**/junit.xml"
