// <auto-generated />
namespace m4d.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class ExplicitModified : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ExplicitModified));
        
        string IMigrationMetadata.Id
        {
            get { return "201403191906568_ExplicitModified"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
