// <auto-generated />
namespace m4d.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class SearchPlaylist : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SearchPlaylist));
        
        string IMigrationMetadata.Id
        {
            get { return "201810090347569_SearchPlaylist"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
